{% set name = "enso_metrics" %}
{% set version = "1.1.3" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/CLIVAR-PRP/ENSO_metrics/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a33c2f35a27ffb58ab18983faf8e964cc14c78963b3a0796e142b4283e8009b6    

build:
  number: 0
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cdms2
    - cdutil
    - genutil
    - numpy
    - scipy
    - udunits2
    - packaging

test:
  imports:
    - EnsoMetrics.EnsoCollectionsLib
    - EnsoMetrics.EnsoComputeMetricsLib
  commands:
    - pip check
  requires:
    - pip

about:
    home: https://github.com/CLIVAR-PRP/ENSO_metrics
    license: BSD-3-Clause
    license_file: LICENSE
    summary: "Library to compute ENSO metrics"

extra:
  recipe-maintainers:
    - eguil
    - lee1043
    - acordonez
    - yyplanton
